//HOW SPECIFIC DO WE WANT TO GET, DO WE WANT TO DEFINE ALL DIFFERENT TYPES OF CHARACTERS HERE?
//SHOULD CHARACTERS HAVE MALE/FEMALE DISTINCTION?
export type PawnType = 'WORKER_TARDIGRADE' | 'CANNIBAL_TARIGRADE' | 'MOON_AGENT';
